# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{skinny_daemon_example}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["dave"]
  s.date = %q{2010-07-22}
  s.default_executable = %q{skinny_daemon_example}
  s.description = %q{Process daemonization with thin!}
  s.email = %q{dave@netbook}
  s.executables = ["skinny_daemon_example"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/skinny_daemon_example",
     "lib/skinny_daemon_example.rb",
     "lib/skinny_daemon_example/config.ru",
     "skinny_daemon_example.gemspec",
     "test/helper.rb",
     "test/test_skinny_daemon_example.rb"
  ]
  s.homepage = %q{http://github.com/futurechimp/skinny_daemon_example}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An example of a skinny daemon}
  s.test_files = [
    "test/test_skinny_daemon_example.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

